# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    container_name: tips-box-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    ports:
      - 5432:5432

  adminer:
    container_name: tips-box-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
